### ISSUE TITLE
API Expired

### ISSUE THREAD

**Issue by MichaelJmad** [ifBars/VRChat-ProTVConvertor#6]
The app is saying during load playlist the api is expired

**Comment by ifBars** [comment]
> The app is saying during load playlist the api is expired

This is likely because it has not been updated in months and still uses the original/old API key. Will try to push a new release with a new API key soon, until then, if you download the source code and input your own YouTube Data API Key, it will work just fine. I will add another comment here and close it, when the new release is pushed, thanks!

**Comment by MichaelJmad** [comment]
Would it be possible for a little guide on how to add the API or add a place in the app to add an API.
I am not very good at figuring out code

**Comment by ifBars** [comment]
> Would it be possible for a little guide on how to add the API or add a place in the app to add an API. I am not very good at figuring out code

Adding your own API key is quite simple, as it is one of the first lines of text/code in the app, however, I will possibly work on implementing a feature, that allows for entry of your own API key in the app, thanks for the suggestion! Working on that new release with an updated API Key now.

**Comment by MichaelJmad** [comment]
Thank you so much

**Comment by ifBars** [comment]
> Thank you so much

My pleasure! [New release has been pushed](https://github.com/ifBars/VRChat-ProTVConvertor/releases/tag/v2.3.1), open another issue if you run into any more issues with the new release. Will work on an add your own API Key to the app feature soon, as requested. Thanks for using my app!

**Comment by MichaelJmad** [comment]
Still getting an api error

**Comment by ifBars** [comment]
> Still getting an api error
> 
> 

Very weird, I will do some investigating soon. It's likely that they might have changed how the API is used, however I believe it was working just fine for me. Will check soon and update you here. Just to make sure, make sure you are connected to the internet when using it, and possibly check to make sure your firewall isn't blocking the app, as those are the only things I can think of that could cause the issue.

**Comment by MichaelJmad** [comment]
Sorry for the late reply.
I have tested the request and also loaded it on my remote server.
It still says API Key is expired.
I am ok putting my own key in however I am not sure how to get and or add my key

**Comment by ifBars** [comment]
> Sorry for the late reply. I have tested the request and also loaded it on my remote server. It still says API Key is expired. I am ok putting my own key in however I am not sure how to get and or add my key

Finally think I found the issue, doesn't seem to be key related, rather it was the way the build/release was pushed. Try [this new build](https://github.com/ifBars/VRChat-ProTVConvertor/releases/tag/v2.4.0), should work just fine now, also you can load already created ProTV playlists now :D

**Comment by MichaelJmad** [comment]
So fun fun new issue, Tested on 

https://youtube.com/playlist?list=PLN6brjpzt7m5KhY9DM_1IKL6A_4J9OwUE&si=45NP_BrAhVmF3Eor
PLN6brjpzt7m5KhY9DM_1IKL6A_4J9OwUE&si=45NP_BrAhVmF3Eor
PLN6brjpzt7m5KhY9DM_1IKL6A_4J9OwUE&si

https://youtube.com/playlist?list=PLN6brjpzt7m5H0ORUZUeoEG89fPk2NCxo&si=7Cbt7FrC_pD7hewx
PLN6brjpzt7m5H0ORUZUeoEG89fPk2NCxo&si=7Cbt7FrC_pD7hewx
PLN6brjpzt7m5H0ORUZUeoEG89fPk2NCxo&si

![image](https://github.com/ifBars/VRChat-ProTVConvertor/assets/16770710/8a7650f8-d9c9-4b83-8987-a4e8eadf50c4)

**Comment by ifBars** [comment]
> So fun fun new issue, Tested on 
> 
> 
> 
> https://youtube.com/playlist?list=PLN6brjpzt7m5KhY9DM_1IKL6A_4J9OwUE&si=45NP_BrAhVmF3Eor
> 
> PLN6brjpzt7m5KhY9DM_1IKL6A_4J9OwUE&si=45NP_BrAhVmF3Eor
> 
> PLN6brjpzt7m5KhY9DM_1IKL6A_4J9OwUE&si
> 
> 
> 
> https://youtube.com/playlist?list=PLN6brjpzt7m5H0ORUZUeoEG89fPk2NCxo&si=7Cbt7FrC_pD7hewx
> 
> PLN6brjpzt7m5H0ORUZUeoEG89fPk2NCxo&si=7Cbt7FrC_pD7hewx
> 
> PLN6brjpzt7m5H0ORUZUeoEG89fPk2NCxo&si
> 
> 
> 
> ![image](https://github.com/ifBars/VRChat-ProTVConvertor/assets/16770710/8a7650f8-d9c9-4b83-8987-a4e8eadf50c4)
> 
> 

The reason for this is due to the &si and the characters after, the app doesn't recognize it as a playlist link. Try this: PLN6brjpzt7m5H0ORUZUeoEG89fPk2NCxo
All I did was just copy the playlist ID, that should work just fine. I'll work on better playlist ID detection from links soon :)

**Comment by MichaelJmad** [comment]
Sweet that worked. 
Now to figure out how to make a list the player can read

**Comment by ifBars** [comment]
> Sweet that worked. 
> 
> Now to figure out how to make a list the player can read

If you need any help feel free to dm me on discord, but when you export the file it should already be in the correct format for ProTV player to use/play :)
