### ISSUE TITLE
it only grabs 17 of 118

### ISSUE THREAD

**Issue by Skaveny** [ifBars/VRChat-ProTVConvertor#7]
I'm using your version ProTVConvertor 2.4.0 I'm trying to to get this playlist that has 118 clips with thumbnails but it only grabs 17 of the clip links can you test and see if you have the same problem? https://youtube.com/playlist?list=PLf25YXZr1q1Kb63skVStvZ0MQjhyNW-zA&si=bagIWesvL84YHY33

**Comment by ifBars** [comment]
I will test here in a bit, keep in mind if any of the videos are invalid or private, they will not be added, also toggling fast export on/off aka trying both, also can help. Will update you here soon.

**Comment by ifBars** [comment]
> I'm using your version ProTVConvertor 2.4.0 I'm trying to to get this playlist that has 118 clips with thumbnails but it only grabs 17 of the clip links can you test and see if you have the same problem? https://youtube.com/playlist?list=PLf25YXZr1q1Kb63skVStvZ0MQjhyNW-zA&si=bagIWesvL84YHY33

Fixed, [download 2.4.1](https://github.com/ifBars/VRChat-ProTVConvertor/releases/tag/v2.4.1)

The issue was that if the program ran into a video that had been private/deleted in the playlist, it would stop instead of continue to the next video.
